apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: backend
  newName: mattedamo26/first-attempt-backend
  newTag: sha-tag
- name: frontend
  newName: mattedamo26/first-attempt-frontend
  newTag: custom_tag
kind: Kustomization
namespace: thesis-app-backend-features-11
resources:
- ../../../../base
