- op: add
  path: /spec/template/spec/containers/0/env
  value:
  - name: MYSQL_ROOT_PASSWORD
    valuefrom:
      secretKeyRef:
        key: MYSQL_ROOT_PASSWORD
        name: db-db-dep
  - name: MYSQL_DATABASE
    valuefrom:
      secretKeyRef:
        key: MYSQL_DATABASE
        name: db-db-dep
