apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: backend
  newName: mattedamo26/first-attempt
  newTag: latest
- name: frontend
  newName: mattedamo26/first-attempt-backend
  newTag: 8467407a14898b3394db80782ff7e7f3eb9da910
kind: Kustomization
namespace: first-attempt-prod
patches:
- path: backend_backend_patch.yaml
  target:
    labelSelector: tier=backend
    name: backend
secretGenerator:
- literals:
  - MYSQL_ROOT_PASSWORD=password
  - MYSQL_DATABASE=thesisAppMariadb
  name: db-config
resources:
- ../../base/
