apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: backend
  newName: mattedamo26/first-attempt-backend
  newTag: latest-prod
- &id001
  name: frontend
  newName: mattedamo26/first-attempt-frontend
  newTag: latest-prod
- *id001
- name: backend
  newName: mattedamo26/first-attempt-backend
  newTag: latest-prod
kind: Kustomization
namespace: -prod
patches:
- path: backend_backend_service_patch.yaml
  target:
    labelSelector: tier=backend
    name: backend
- path: backend_backend_deployment_patch.yaml
  target:
    labelSelector: tier=backend
    name: backend
- path: frontend_frontend_deployment_patch.yaml
  target:
    labelSelector: tier=frontend
    name: frontend
resources:
- ../../base
secretGenerator:
- literals:
  - MYSQL_ROOT_PASSWORD=password
  - MYSQL_DATABASE=mybd
  name: backend-backend
