apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: backend
  newName: mattedamo26/first-attempt-backend
  newTag: cb3fea76d06f4173b42247d9a220904d576c95f4-prod
- name: frontend
  newName: mattedamo26/first-attempt-frontend
  newTag: latest-prod
kind: Kustomization
namespace: thesis-app-prod
patches:
- path: backend_backend-dep_deployment_patch.yaml
  target:
    labelSelector: tier=backend
    name: backend-dep
- path: backend_backend-service_service_patch.yaml
  target:
    labelSelector: tier=backend
    name: backend-service
- path: frontend_frontend-dep_deployment_patch.yaml
  target:
    labelSelector: tier=frontend
    name: frontend-dep
- path: frontend_frontend-service_service_patch.yaml
  target:
    labelSelector: tier=frontend
    name: frontend-service
- path: db_db-dep_deployment_patch.yaml
  target:
    labelSelector: tier=db
    name: db-dep
resources:
- ../../base
secretGenerator:
- literals:
  - MYSQL_ROOT_PASSWORD=password
  - MYSQL_DATABASE=thesisAppMariadb
  name: db-db-dep
