apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: backend
  newName: mattedamo26/first-attempt-backend
  newTag: latest-prod
- name: frontend
  newName: mattedamo26/first-attempt-frontend
  newTag: latest-prod
kind: Kustomization
namespace: thesis-app-prod
patches:
- path: backend_backend-service_service_patch.yaml
  target:
    labelSelector: tier=backend
    name: backend-service
- path: backend_backend-dep_deployment_patch.yaml
  target:
    labelSelector: tier=backend
    name: backend-dep
- path: frontend_frontend-dep_deployment_patch.yaml
  target:
    labelSelector: tier=frontend
    name: frontend-dep
resources:
- ../../base
secretGenerator:
- literals:
  - MYSQL_ROOT_PASSWORD=password
  - MYSQL_DATABASE=mybd
  name: backend-backend-dep
