apiVersion: v1
kind: Service
metadata: 
  name: backend-service
  labels:
    app: thesis-app
    tier: backend
spec:
  type: NodePort
  selector:
    app: thesis-app
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
