name: delete-kustomize-dir

on: 
  workflow_dispatch:
    inputs:
      code-branch:
        description: 'branch of code repository that has been deleted'
        required: true
      tier:
        description: 'it can be frontend or backend'
        required: true

jobs:
  delete:
    name: Delete Dir
    runs-on: ubuntu-latest
    
    steps:
     
      - name: set environment variables
        uses: allenevans/set-env@v2.0.0
        with:
          CODE_BRANCH:  ${{ github.event.inputs.code-branch}}
          TIER: ${{ github.event.inputs.tier}}
          APP_NAME: ${{secrets.APP_NAME}}

      - name: Check out code
        uses: actions/checkout@v2
    
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: "3.x"
     
      - run: python delete-overlays-dir.py
        name: Delete dir from kustomize overlays
    

      - name: Add and commit changes
        uses: EndBug/add-and-commit@v6
        with:
          message: "deleted kustomize dir"
  
  trigger-workflow:
    name: Trigger workflow in ArgoCD repo
    runs-on: ubuntu-latest
    needs: delete
    steps:
      
      - name: Trigger infrastructure repo workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: delete-manifest
          ref: master
          inputs: '{"code-branch" : "${{ github.event.inputs.code-branch}}", "tier" : "${{ github.event.inputs.tier}}", "app-name" : "${{secrets.APP_NAME}}"}'
          repo: mattedamo/thesis-argocd
          token: ${{ secrets.TOKEN_GITHUB_DISPATCHER }}
           
