name: update-infrastructure-backend
on: 
  workflow_dispatch:
    inputs:
      docker-image-tag:
        description: 'this is the docker tag build in the code workflow'     
        required: true
      code-branch:
        description: 'branch of code repo'
        required: true
      repo-name: 
        description: 'name of code repo'
        required: true
      tier: 
        description: 'the tier of the code repo'
        required: true
      docker-frontend-repo:
        description: 'the repo name on dockerhub for the frontend image'
        required: true
      docker-backend-repo:
        description: 'the repo name on dockerhub for the backend image'
        required: true
      

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    
    steps:
      
      - name: set environment variables
        uses: allenevans/set-env@v2.0.0
        with:
          DOCKER_TAG: ${{ github.event.inputs.docker-image-tag}}
          CODE_BRANCH:  ${{ github.event.inputs.code-branch}}
          CODE_REPO_NAME: ${{ github.event.inputs.repo-name}}
          TIER: ${{ github.event.inputs.tier}}
          DOCKER_BACKEND_REPO: ${{ github.event.inputs.docker-backend-repo}}
          DOCKER_FRONTEND_REPO: ${{ github.event.inputs.docker-frontend-repo}}
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
      #- name: Set env vars
      #  run: echo "setting env vars"
      #  env:
      #    DOCKER_IMAGE: ${{ github.event.inputs.docker-image}}
      #    CODE_BRANCH:  ${{ github.event.inputs.code-branch}}
      #    CODE_REPO_NAME: ${{ github.event.inputs.repo-name}} 

      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Checkout code repo
        uses: actions/checkout@v2
        with:
            repository: mattedamo/${{ github.event.inputs.repo-name}}
            token: ${{secrets.TOKEN_GITHUB_DISPATCHER}}
            ref: ${{ github.event.inputs.code-branch}}
            path: code-repo
      - run: cp code-repo/file.yaml ./file.yaml
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: "3.x"

      - run: pip install PyYAML
        name: Install py dependencies
        
      - name: Create kustomize overlays dir, if necessary
        run: python kustomize-dir-official.py
        
      - run: python final-script-official.py
        name: Run python script, update kustomize overlays
        
      - run: python update-docker-img-official.py
        name: Run update docker image
      
      - run: rm -f file.yaml
        
      - run: rm -rf code-repo/

      - name: Add and commit changes
        uses: EndBug/add-and-commit@v6
        with:
          message: 'updated kustomize files'
